import type { SaveExerciseInput } from "@/modules/training/types";

export const MAX_ROUTINE_PREVIEW_EXERCISES = 4;
export const TRAINING_TABS = ["train", "plan", "progress"] as const;
export type TrainingTab = (typeof TRAINING_TABS)[number];
export const LEGACY_TRAINING_TAB_MAP: Record<string, TrainingTab> = {
  today: "train",
  routines: "plan",
  library: "plan",
  history: "progress",
  progress: "progress",
};

export const defaultExerciseForm: SaveExerciseInput = {
  name: "",
  muscle_group: "chest",
  secondary_muscles: [],
  equipment: "dumbbell",
  movement_type: "push",
  difficulty: "beginner",
  instructions: "",
  video_url: "",
};

export const toNumber = (value: string) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

export const formatDateTime = (value: string | null) => {
  if (!value) return "--";
  return new Date(value).toLocaleString("es-PE", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
};

export const formatRest = (seconds: number) => {
  const minutes = Math.floor(seconds / 60);
  return minutes ? `${minutes}m ${seconds % 60}s` : `${seconds}s`;
};

export const prLabelMap = {
  max_weight: "Max weight",
  estimated_1rm: "1RM estimado",
  max_volume: "Max volumen",
} as const;

export const draftStorageKey = (sessionId: string) => `appfit_training_drafts:${sessionId}`;
export const notesStorageKey = (sessionId: string) => `appfit_training_notes:${sessionId}`;

export const parseStoredJson = <T,>(value: string | null, fallback: T): T => {
  if (!value) return fallback;
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
};

export const TRAINING_COPY = {
  en: {
    title: "Training Logbook",
    subtitle: "Open, understand what to do, and start training in seconds.",
    today: "Today",
    rest: "Rest",
    activeSession: "Active session",
    noWorkout: "No workout",
    tabs: { train: "Train", plan: "Plan", progress: "Progress" },
    startWorkout: "Start workout",
    startedAt: "Started",
    cancel: "Cancel",
    finish: "Finish",
    sessionNotes: "Session notes",
    completedSets: "completed sets",
    week: "Week",
    weekDescription: "Assign a routine, rest day or leave the day empty.",
    todayBadge: "Today",
    unassigned: "Unassigned",
    quickStart: "Quick start",
    quickStartDescription: "Start any routine even if it is not scheduled for today.",
    firstCreateRoutine: "Create a routine first.",
    personalRoutines: "Personal routines",
    personalRoutinesDescription: "Create, edit and delete training blocks.",
    newRoutine: "New",
    noRoutines: "You do not have routines yet.",
    noDescription: "No description",
    routineExercises: "Exercises",
    noRoutineExercises: "No exercises",
    moreExercisesSuffix: "more",
    start: "Start",
    edit: "Edit",
    delete: "Delete",
    templates: "Templates",
    templatesDescription: "Duplicate bases like Push, Pull or Legs.",
    duplicateTemplate: "Duplicate template",
    exerciseLibrary: "Exercise library",
    exerciseLibraryDescription: "Global base plus custom exercises.",
    customExercise: "Custom exercise",
    searchExercise: "Search exercise...",
    allGroups: "All muscle groups",
    allEquipment: "All equipment",
    allPatterns: "All patterns",
    customBadge: "Custom",
    baseBadge: "Base",
    historyTitle: "History",
    historyDescription: "Finished sessions with volume and status.",
    noHistory: "No finished sessions yet.",
    progressTitle: "Exercise progress",
    progressDescription: "Strength curve, volume and PRs.",
    selectExercise: "Select exercise",
    noProgress: "No historical data yet.",
    exerciseHistoryTitle: "Exercise history",
    exerciseHistoryDescription: "Sets, peak load and volume by date.",
    noWorkoutScheduled: "No workout scheduled today.",
    planningSectionTitle: "Weekly plan",
    planningSectionDescription: "Assign routines for each day and lock your week.",
    planningSummaryTitle: "Week snapshot",
    planningSummaryDescription: "Review the week and jump to planning if needed.",
    viewPlanning: "Open planning",
    noWorkoutScheduledHint: "Use quick start or prepare your week to keep momentum.",
    restDayNotice: "Today is a scheduled rest day.",
    restDayHint: "Focus on recovery, mobility, and sleep quality. You can still run a quick session if needed.",
    noLibraryResults: "No exercises match these filters.",
    clearFilters: "Clear filters",
    noPrsYet: "No PRs yet for this exercise.",
    noExerciseHistory: "No exercise sessions recorded yet.",
    librarySupportHint: "Support library for routine editing and setup",
    routineSaved: "Routine saved.",
    routineDeleted: "Routine deleted.",
    templateDuplicated: "Template duplicated.",
    exerciseSaved: "Custom exercise saved.",
    sessionStarted: "Session started.",
    sessionClosed: "Session closed.",
    prsDetected: "PRs detected.",
    scheduleSaved: "Week plan saved.",
    setSaved: "Set saved.",
    noteSaved: "Exercise note saved.",
    loading: "Loading training...",
    failedLoad: "Training could not be loaded.",
    deleteRoutineTitle: "Delete routine",
    deleteRoutineDescription: "This will remove the routine and its exercise block. Scheduled days will be left unassigned.",
    deleteRoutineConfirm: "Delete routine",
    activeExerciseCard: "Exercise block",
    target: "Target",
    restLabel: "Rest",
    previousPerformance: "Last performance",
    noPreviousPerformance: "No previous completed session yet.",
    exerciseNote: "Exercise note",
    saveNote: "Save note",
    setLabel: "Set",
    weight: "Weight",
    reps: "Reps",
    rir: "RIR",
    notes: "Notes",
    saveDraft: "Save",
    markDone: "Complete",
    markUndone: "Mark pending",
    removeSet: "Remove",
    addSet: "Add extra set",
    targetSets: "Target sets",
    targetReps: "Target reps",
    addExercise: "Add exercise",
    saveRoutine: "Save routine",
    createRoutine: "Create routine",
    editRoutine: "Edit routine",
    saveExercise: "Save exercise",
    createCustomExercise: "Create custom exercise",
  },
  es: {
    title: "Training Logbook",
    subtitle: "Abre, entiende que toca hoy y empieza a entrenar en segundos.",
    today: "Hoy",
    rest: "Descanso",
    activeSession: "Sesion activa",
    noWorkout: "Sin entrenamiento",
    tabs: { train: "Entrenar", plan: "Planificar", progress: "Progreso" },
    startWorkout: "Iniciar entrenamiento",
    startedAt: "Iniciada",
    cancel: "Cancelar",
    finish: "Finalizar",
    sessionNotes: "Notas generales de la sesion",
    completedSets: "series completadas",
    week: "Semana",
    weekDescription: "Asigna rutina, descanso o deja el dia vacio.",
    todayBadge: "Hoy",
    unassigned: "Sin asignar",
    quickStart: "Inicio rapido",
    quickStartDescription: "Inicia cualquier rutina aunque no este programada hoy.",
    firstCreateRoutine: "Primero crea una rutina.",
    personalRoutines: "Rutinas personales",
    personalRoutinesDescription: "Crea, edita y elimina bloques de entrenamiento.",
    newRoutine: "Nueva",
    noRoutines: "Aun no tienes rutinas.",
    noDescription: "Sin descripcion",
    routineExercises: "Ejercicios",
    noRoutineExercises: "Sin ejercicios",
    moreExercisesSuffix: "mas",
    start: "Iniciar",
    edit: "Editar",
    delete: "Eliminar",
    templates: "Plantillas",
    templatesDescription: "Duplica bases como Push, Pull o Legs.",
    duplicateTemplate: "Duplicar plantilla",
    exerciseLibrary: "Biblioteca de ejercicios",
    exerciseLibraryDescription: "Base global mas ejercicios personalizados.",
    customExercise: "Ejercicio custom",
    searchExercise: "Buscar ejercicio...",
    allGroups: "Todos los grupos",
    allEquipment: "Todo el equipo",
    allPatterns: "Todo el patron",
    customBadge: "Custom",
    baseBadge: "Base",
    historyTitle: "Historial",
    historyDescription: "Sesiones finalizadas con volumen y estado.",
    noHistory: "Aun no hay sesiones finalizadas.",
    progressTitle: "Progreso por ejercicio",
    progressDescription: "Curva de fuerza, volumen y PRs.",
    selectExercise: "Selecciona ejercicio",
    noProgress: "Sin datos historicos todavia.",
    exerciseHistoryTitle: "Historial por ejercicio",
    exerciseHistoryDescription: "Detalle de sets, carga maxima y volumen por fecha.",
    noWorkoutScheduled: "No hay entrenamiento programado hoy.",
    planningSectionTitle: "Plan semanal",
    planningSectionDescription: "Asigna rutinas por dia y deja la semana lista.",
    planningSummaryTitle: "Resumen semanal",
    planningSummaryDescription: "Mira tu semana y entra a planificar si necesitas cambios.",
    viewPlanning: "Ver planificacion",
    noWorkoutScheduledHint: "Usa inicio rapido o prepara tu semana para mantener el ritmo.",
    restDayNotice: "Hoy tienes descanso programado.",
    restDayHint: "Prioriza recuperacion, movilidad y sueno. Si lo necesitas, puedes iniciar una sesion rapida.",
    noLibraryResults: "No encontramos ejercicios con esos filtros.",
    clearFilters: "Limpiar filtros",
    noPrsYet: "Aun no hay PRs para este ejercicio.",
    noExerciseHistory: "Aun no hay sesiones registradas para este ejercicio.",
    librarySupportHint: "Biblioteca de apoyo para editar y crear rutinas",
    routineSaved: "Rutina guardada.",
    routineDeleted: "Rutina eliminada.",
    templateDuplicated: "Plantilla duplicada.",
    exerciseSaved: "Ejercicio personalizado guardado.",
    sessionStarted: "Sesion iniciada.",
    sessionClosed: "Sesion cerrada.",
    prsDetected: "PRs detectados.",
    scheduleSaved: "Agenda semanal guardada.",
    setSaved: "Serie guardada.",
    noteSaved: "Nota del ejercicio guardada.",
    loading: "Cargando entrenamiento...",
    failedLoad: "No se pudo cargar entrenamiento.",
    deleteRoutineTitle: "Eliminar rutina",
    deleteRoutineDescription: "Se eliminara la rutina y su bloque de ejercicios. Los dias programados quedaran sin asignar.",
    deleteRoutineConfirm: "Eliminar rutina",
    activeExerciseCard: "Bloque de ejercicio",
    target: "Objetivo",
    restLabel: "Descanso",
    previousPerformance: "Ultimo rendimiento",
    noPreviousPerformance: "Todavia no hay una sesion completada previa.",
    exerciseNote: "Nota del ejercicio",
    saveNote: "Guardar nota",
    setLabel: "Serie",
    weight: "Peso",
    reps: "Reps",
    rir: "RIR",
    notes: "Notas",
    saveDraft: "Guardar",
    markDone: "Completar",
    markUndone: "Marcar pendiente",
    removeSet: "Quitar",
    addSet: "Agregar serie extra",
    targetSets: "Series objetivo",
    targetReps: "Reps objetivo",
    addExercise: "Agregar ejercicio",
    saveRoutine: "Guardar rutina",
    createRoutine: "Crear rutina",
    editRoutine: "Editar rutina",
    saveExercise: "Guardar ejercicio",
    createCustomExercise: "Crear ejercicio personalizado",
  },
} as const;

export type TrainingCopy = (typeof TRAINING_COPY)["en"];
